apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    namespace: sandbox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/helm
    repoURL: https://github.com/luafanti/spring-boot-debug-app
    targetRevision: main
    helm:
      values: |-
        serviceAccount:
          create: true
        image:
          repository: luafanti/spring-boot-debug-app
          tag: main
          pullPolicy: IfNotPresent
        replicaCount: 1
        resources:
          memoryRequest: 256Mi
          memoryLimit: 512Mi
          cpuRequest: 500m
          cpuLimit: 1 
        probes:
          liveness:
            initialDelaySeconds: 15
            path: /actuator/health/liveness
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
            periodSeconds: 5
          readiness:
            initialDelaySeconds: 15
            path: /actuator/health/readiness
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
            periodSeconds: 5
        ports:
          http:
            name: http
            value: 8080
          management:
            name: management
            value: 8081
        log:
          level:
            spring: "info"
            service: "info"
  syncPolicy: {}
